import json
import sys
from pptx import Presentation

def create_presentation(json_filepath, output_filename="output.pptx"):
    try:
        # 1. Load the JSON data generated by the LLM
        with open(json_filepath, 'r', encoding='utf-8') as file:
            data = json.load(file)

        # 2. Initialize the presentation
        prs = Presentation()

        # 3. Create the Title Slide (Layout 0)
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        title.text = data.get("main_title", "My Presentation")
        subtitle.text = data.get("subtitle", "Generated by AI")

        # 4. Create the Content Slides (Layout 1)
        bullet_slide_layout = prs.slide_layouts[1]
        
        for slide_data in data.get("slides", []):
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes

            # Add slide title
            title_shape = shapes.title
            title_shape.text = slide_data.get("title", "Slide Title")
            
            # Add bullet points
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            
            # The first line is added directly, subsequent lines need a new paragraph
            points = slide_data.get("points", [])
            for i, point in enumerate(points):
                if i == 0:
                    tf.text = point
                else:
                    p = tf.add_paragraph()
                    p.text = point

        # 5. Save the file offline
        prs.save(output_filename)
        print(f"Success! Presentation saved offline as: {output_filename}")

    except Exception as e:
        print(f"Error generating presentation: {e}")

# This allows the script to be run from the command line
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python ppt_generator.py <path_to_json_file>")
    else:
        json_file = sys.argv[1]
        create_presentation(json_file)
